service: listspace-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    AWS_REGION: ap-southeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:DeleteObject
            - s3:GetObject
          Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}/*"
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: "arn:aws:s3:::${env:S3_BUCKET_NAME}"
  httpApi:
    authorizers:
      ApiGatewayAuthorizer:
        type: jwt
        identitySource:
          - $request.header.Authorization
        jwtConfiguration:
          audience:
            - ${env:COGNITO_USER_POOL_CLIENT_ID}
          issuer:
            - ${env:COGNITO_USER_POOL_ISSUER}

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /api/public/properties
          method: get
          cors: true
      - http:
          path: /api/public/properties/{id}
          method: get
          cors: true
      - http:
          path: /api/properties
          method: get
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/properties
          method: post
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/properties/{id}
          method: get
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/properties/{id}
          method: put
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/properties/{id}
          method: delete
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/properties/{id}/images
          method: post
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request
      - http:
          path: /api/public/search
          method: get
          cors: true
      - http:
          path: /api/properties/search
          method: get
          cors: true
          authorizer:
            name: ApiGatewayAuthorizer
            type: request

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    noAuth: true  # Disable auth for local development
    noTimeout: true
